### PR TITLE
AVIF Support

### LINKED ISSUE #891: HEIC formatt file is not supported
It's throwing an exception:`NotSupportedException Encoding format (HEIC) is not supported`
When I tried to upload image file with format .heic

### PR DESCRIPTION
**Pull request by freshleafmedia**
This PR adds support for the AVIF encoding.

The AVIF format has been supported in ImageMagick since [at least 7.0.10-21](https://github.com/ImageMagick/ImageMagick/commit/9f4c23df9e6a462dcef91f98aecce64d78552a5d). I personally have tested it on 7.0.10-25 along with [this](https://github.com/ImageMagick/ImageMagick/issues/1432#issuecomment-671036653) person.

This closes #891

### CODE REVIEW

**Comment by Hao-Wu** [comment]
@freshleafmedia  Will support for AVIF result in supporting for HEIC？
Do we need a similar encoder declaration with what you've done in this PR.

**Comment by freshleafmedia** [comment]
@Hao-Wu No, you're right an additional declaration will be required

File: src/Intervention/Image/Gd/Encoder.php [hunk 1]
```diff
@@ -121,4 +121,16 @@ protected function processPsd()
...
     }
+
+    /**
+     * Processes and returns encoded image as AVIF string
+     *
+     * @return string
+     */
+    protected function processAvif()
+    {
+        throw new NotSupportedException(
```
Comment (dgrammatiko) [inline src/Intervention/Image/Gd/Encoder.php:132]: Actually, GD supports avif: https://github.com/libgd/libgd/releases/tag/gd-2.3.2

Comment (dgrammatiko) [reply src/Intervention/Image/Gd/Encoder.php:132]: @freshleafmedia could you update this file to include the GD support?

```php
    protected function processAvif()
    {
        if ( ! function_exists('imageavif')) {
            throw new NotSupportedException(
                "Avif format is not supported by PHP installation."
            );
        }

        ob_start();
        imageavif($this->image->getCore(), null, $this->quality);
        $this->image->mime = defined('IMAGETYPE_AVIF') ? image_type_to_mime_type(IMAGETYPE_AVIF) : 'image/avif';
        $buffer = ob_get_contents();
        ob_end_clean();

        return $buffer;
    }
```

Comment (JoyceBabu) [reply src/Intervention/Image/Gd/Encoder.php:132]: GD Support is not yet available in PHP GD.

https://bugs.php.net/bug.php?id=80828

Comment (dgrammatiko) [reply src/Intervention/Image/Gd/Encoder.php:132]: That's not quite accurate, https://github.com/php/php-src/pull/7026 is merged so GD with avif will be available in the next patch version (8.1)

Comment (morsssss) [reply src/Intervention/Image/Gd/Encoder.php:132]: You're both right. AVIF is now supported in libgd. The support in PHP is now merged, and it's set to be released in PHP 8.1. ☺️
